[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiocache>=0.12.3",
    "aioquic>=1.2.0",
    "aiostream>=0.7.0",
    "asyncio>=3.4.3",
    "fastapi[standard]>=0.115.13",
    "zmq>=0.0.0",
]
